"""webhooks

Revision ID: 16c61dc73b01
Revises: 007bbfb5ce5c
Create Date: 2026-07-22 15:44:28.025720

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '16c61dc73b01'
down_revision = '007bbfb5ce5c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_webhooks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('app_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id', 'event_type', name='uq_app_webhooks_app_event_type')
    )
    op.add_column('apps', sa.Column('webhook_secret', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apps', 'webhook_secret')
    op.drop_table('app_webhooks')
    # ### end Alembic commands ###
